base/urls.py
from django.urls import path, include
from django.urls import path
from django.contrib import admin
from .views import Initial_page, CustomLoginView, PatientsList, ClientDetail, ClientCreate, ClientUpdate, ClientDelete
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
  #initial
  path('', views.Initial_page, name='initial_page'),
  path('login/', CustomLoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
  path('oauth/', include('social_django.urls', namespace='social')),
  path('clients_list/', PatientsList.as_view(), name='PatientsList'),
  path('client/<int:pk>/', ClientDetail.as_view(), name='client'),
  path('client-create/', ClientCreate.as_view(), name='client-create'),
  path('client-update/<int:pk>/', ClientUpdate.as_view(), name='client-update'),
  path('client-delete/<int:pk>/', ClientDelete.as_view(), name='client-delete'),
]

snet_project/urls.py
from django.conf.urls import include

"""snet_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
# Create your models here.

class Doctor(models.Model):
  name = models.CharField(max_length=200)
  email = models.EmailField()
  password = models.CharField(max_length=20)
  
  created_at = models.DateTimeField(auto_now_add=True)
  edited = models.DateTimeField(auto_now=True)

  def __str__(self):
    return '{}'.format(self.name) 

class Patient(models.Model):
  name = models.CharField(max_length=200)
  phone = models.CharField(max_length=11)
  cep = models.CharField(max_length=8)
  address = models.CharField(max_length=200)
  number = models.CharField(max_length=4)
  city = models.CharField(max_length=50)
  state = models.CharField(max_length=2)
  country = models.CharField(max_length=50)

  created_at = models.DateTimeField(auto_now_add=True)
  edited = models.DateTimeField(auto_now=True)

  def __str__(self):
    return '{}'.format(self.name) 

class Consultations(models.Model):
  date = models.DateTimeField(null=False)
  description = models.TextField(max_length=500)
  
  PROGRESS_STATUS = (
    ('A Confirmar','A Confirmar'),
    ('Confirmado', 'Confirmado'),
    ('Finalizado','Finalizado')
  )
  
  status = models.CharField(max_length=15, choices=PROGRESS_STATUS, default='A Confirmar')
  doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
  patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

  created = models.DateTimeField(auto_now_add=True)
  edited = models.DateTimeField(auto_now=True)

  def __str__(self):
        id_pretty = "Consulta para {} em {} com o medico {}".format(
            self.patient, self.date, self.doctor)
        return id_pretty

base/forms.py
from django import forms

class ClientFormAdmin(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(ClientFormAdmin, self).__init__(*args, **kwargs)
    self.fields['phone'].widget.attrs['class'] = 'mask-phone'
    self.fields['cep'].widget.attrs['class'] = 'mask-cep'

base/views.py
from django.shortcuts import render
from .models import Doctor, Patient, Consultations
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def Initial_page(request):
  return render(request,'clinicMedicalSys/index.html')

class CustomLoginView(LoginView):
  template_name = 'clinicMedicalSys/login.html'
  fields = '__all__'
  redirect_authenticated_user = True
  context_object_name = 'logins'

  def get_success_url(self):
    return reverse_lazy('PatientsList')

class PatientsList(LoginRequiredMixin, ListView):
  template_name = 'clinicMedicalSys/clients_list.html'
  model = Patient
  context_object_name = 'clients'

class ClientDetail(LoginRequiredMixin, DetailView):
  template_name = 'clinicMedicalSys/client_detail.html'
  context_object_name = 'client'
  model = Patient

class ClientCreate(LoginRequiredMixin, CreateView):
  template_name = 'clinicMedicalSys/client_form.html'
  #context_object_name = 'client_create'
  model = Patient
  fields = '__all__'
  success_url = reverse_lazy('PatientsList')

class ClientUpdate(LoginRequiredMixin, UpdateView):
  template_name = 'clinicMedicalSys/client_form_update.html'
  context_object_name = 'client_update'
  model = Patient
  fields = '__all__'
  success_url = reverse_lazy('PatientsList')

class ClientDelete(LoginRequiredMixin, DeleteView):
  template_name = 'clinicMedicalSys/client_confirm_delete.html'
  model = Patient
  context_object_name = 'client'
  success_url = reverse_lazy('PatientsList')

base/templates/clinicMedicalSys/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>MedicalSys</title>
  <link rel="icon" href="{% static 'saude.png' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <title>Grey Sloan Memorial Hospital</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-fixed/">



  <!-- Bootstrap core CSS -->
  <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'navbar-top-fixed.css' %}"> -->

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    body {
      background-color: #37b8bd;
      color: rgba(255, 255, 255, 1);
      border-color: rgba(255, 255, 255, 0.7);
      font-family: 'Mazzard H';

    }

    main {
      margin-top: 3rem;
    }
  </style>

</head>

<body>
  <main class="container">
    <div class="container text-center">
      <div class="row justify-content-md-center">
        <div class="col col-lg-2">

        </div>
        <div class="col-md-auto">
          {% block content %}

          {% endblock %}
        </div>
        <div class="col col-lg-2">

        </div>
      </div>
  </main>

  <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
  <script rel="stylesheet" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
    integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>

</body>

</html>

base/templates/clinicMedicalSys/client_confirm_delete.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}
<style>
  #delete-card {
    background-color: #11887e85;
    padding: 30px;
    border-radius: 15px;
  }

  input {
    background-color: rgb(216, 27, 27);
    color: #fff;
  }

  a {
    color: rgba(0, 0, 0, 0.507);
    text-decoration: none;
  }

  a::after {
    content: " →";
  }
</style>

<form method="POST">
  <div class="card" style="width: 18rem;" id="delete-card">
    <div class="card-body">
      {% csrf_token %}
      <P>Você tem certeza que deseja deletar esse cliente? "{{client}}"</P>
      <input type="submit" value="Deletar">
    </div>
  </div>
</form>
<a href="{% url 'PatientsList' %}">Voltar</a>
{%endblock%}

base/templates/clinicMedicalSys/client_detail.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}
<style>
  #detail-card {
    background-color: #11887e85;
    padding: 40px;
    border-radius: 15px;
  }

  a {
    color: rgba(0, 0, 0, 0.507);
    text-decoration: none;
  }

  a::after {
    content: " →";
  }
</style>

<div class="card" style="width: 18rem;" id="detail-card">
  <div class="card-body">
    {% csrf_token %}
    <p>Cliente: {{client}}</p>
    <p>Adicionado(a): {{client.created_at}}</p>
    <p>Editado(a): {{client.edited}}</p>
  </div>
</div>
<a href="{% url 'PatientsList' %}">Voltar</a>
{% endblock %}

base/templates/clinicMedicalSys/client_form.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}
<style>
  input {
    border-radius: 5px;
    border-color: rgb(185, 185, 185)
  }

  #createclient-form {
    background-color: #11887e85;
    padding: 30px;
    border-radius: 15px;
  }

  label {
    width: 80px;
    display: inline-block;
  }

  #input-submit {
    width: 90%;
  }

  a {
    color: rgba(0, 0, 0, 0.507);
    text-decoration: none;
  }

  a::after {
    content: " →";
  }
</style>

<h3>Adicionar cliente</h3>

<form method="POST" action="" id="createclient-form">
  <div class="container text-center">
    <div class="row-2">
      {%csrf_token%}
      {{form.as_p}}
    </div>
  </div>
  <input id="input-submit" type="submit" value="Adicionar">
  <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
</form>
<a href="{% url 'PatientsList' %}">Voltar</a>


{% block scripts %}
<script src="{% static 'jquery.mask.min.js' %}"></script>
<script>
  $(document).ready(function ($) {

    $('#id_cep').mask('00000-000');
    $('#id_phone').mask('(00) 00000-0000');

    function limpa_formulário_cep() {

      $("#id_address").val("");
      $("#id_city").val("");
      $("#id_state").val("");
    }

    $("#id_cep").blur(function () {

      var cep = $(this).val().replace(/\D/g, '');



      if (cep != "") {


        var validacep = /^[0-9]{8}$/;


        if (validacep.test(cep)) {


          $("#id_address").val("...");
          $("#id_city").val("...");
          $("#id_state").val("...");


          $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

            if (!("erro" in dados)) {

              $("#id_address").val(dados.logradouro);
              $("#id_city").val(dados.localidade);
              $("#id_state").val(dados.uf);

            }
            else {

              limpa_formulário_cep();
              alert("CEP não encontrado.");
            }
          });
        }
        else {

          limpa_formulário_cep();
          alert("Formato de CEP inválido.");
        }
      }
      else {

        limpa_formulário_cep();
      }
    });

    $('#createclient-form').submit(function () {
      $('#createclient-form').find(":input[id*='id_']").unmask();
    })
  });
</script>

{% endblock %}
{% endblock %}

base/templates/clinicMedicalSys/client_form_update.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}

<style>
  input {
    border-radius: 5px;
    border-color: rgb(185, 185, 185)
  }

  #updateclient-form {
    background-color: #11887e85;
    padding: 30px;
    border-radius: 15px;
  }

  label {
    width: 80px;
    display: inline-block;
  }

  #input-submit {
    width: 90%;
  }

  a {
    color: rgba(0, 0, 0, 0.507);
    text-decoration: none;
  }

  a::after {
    content: " →";
  }
</style>

<h3>Atualizar cliente</h3>

<form method="POST" action="" id="updateclient-form">
  <div class="container text-center">
    <div class="row-2">
      {%csrf_token%}
      {{form.as_p}}
    </div>
  </div>
  <input type="submit" value="Atualizar" id="input-submit">
  <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
</form>
<a href="{% url 'PatientsList' %}">Voltar</a>

{% block scripts %}
<script src="{% static 'jquery.mask.min.js' %}"></script>
<script>
  $(document).ready(function ($) {

    $('#id_cep').mask('00000-000');
    $('#id_phone').mask('(00) 00000-0000');

    function limpa_formulário_cep() {

      $("#id_address").val("");
      $("#id_city").val("");
      $("#id_state").val("");
    }

    $("#id_cep").blur(function () {

      var cep = $(this).val().replace(/\D/g, '');



      if (cep != "") {


        var validacep = /^[0-9]{8}$/;


        if (validacep.test(cep)) {


          $("#id_address").val("...");
          $("#id_city").val("...");
          $("#id_state").val("...");


          $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

            if (!("erro" in dados)) {

              $("#id_address").val(dados.logradouro);
              $("#id_city").val(dados.localidade);
              $("#id_state").val(dados.uf);

            }
            else {

              limpa_formulário_cep();
              alert("CEP não encontrado.");
            }
          });
        }
        else {

          limpa_formulário_cep();
          alert("Formato de CEP inválido.");
        }
      }
      else {

        limpa_formulário_cep();
      }
    });

    $('#updateclient-form').submit(function () {
      $('#updateclient-form').find(":input[id*='id_']").unmask();
    })
  });
</script>

{% endblock %}
{% endblock %}

base/templates/clinicMedicalSys/clients_list.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}
<style>
  #bootstrapdatatable {
    color: #fff;
    background-color: #11887e85;
  }

  svg {
    color: #fff;
  }

  .add-cliente {
    background-color: rgba(93, 255, 179, 0.65);
    color: #fff;
    border: none;
    margin-bottom: 5px;
    border-radius: 5px;
  }

  .add-cliente:hover {
    background-color: rgba(93, 255, 179, 0.74);
  }

  a {
    color: rgba(0, 0, 0, 0.507);
    text-decoration: none;
  }
</style>

<h1>Clientes MedicalSys</h1>
<a href="{% url 'client-create' %}"><button class="add-cliente">Adicionar cliente</button></a>

<div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered">
    <tr>
      <th>Cliente</th>
      <th>País</th>
      <th>Estado</th>
      <th>Cidade</th>
      <th>CEP</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th>Visualizar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
    {% for client in clients %}
    <tr>
      <td>{{client.name}}</td>
      <td>{{client.country}}</td>
      <td>{{client.state}}</td>
      <td>{{client.city}}</td>
      <td>{{client.cep}}</td>
      <td>{{client.address}}</td>
      <td>{{client.phone}}</td>
      <td><a href="{% url 'client' client.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
            fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path
              d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
          </svg></a></td>
      <td><a href="{% url 'client-update' client.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
            fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path
              d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
            <path fill-rule="evenodd"
              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
          </svg></a></td>
      <td><a href="{% url 'client-delete' client.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
            fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
            <path
              d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
          </svg></a></td>
    </tr>
    {% empty %}
    <h3>No clients in list</h3>
    {% endfor %}
  </table>
  <a class="nav-link active" aria-current="page" href="{% url 'initial_page' %}">Home</a>
  {% endblock %}
</div>

base/templates/clinicMedicalSys/index.html
{% extends 'clinicMedicalSys/base.html' %}

{% block content %}
{% load static %}

<style>
  .container {
    text-align: center;
    color: white;
    margin-top: 3rem;
  }

  h1 {
    text-transform: uppercase;
    letter-spacing: 5px;
    font-size: 4rem;
    font-weight: 400;
  }

  p {
    font-size: 1.15rem;
    letter-spacing: 3px;
    margin: 20px 0 40px;
  }

  button {
    color: white;
    border: 2px white solid;
    padding: 10px 15px;
    border-radius: 5px;
  }

  .container a {
    text-decoration: none;
    color: rgba(0, 0, 0, 0.507);
  }
</style>

<div>
  <section class="section-one">
    <div class="container">
      <h1>Bem vindo ao MedicalSys</h1>
      <p>Gestão prática e descomplicada para sua clínica e consultório</p>
      {% if request.user.is_authenticated %}

      <p>{{request.user}}</p>
      <button><a href="{% url 'logout' %}">Logout</a></button>
      {% else %}
      <button><a href="{% url 'login' %}">Login</a></button>
      {% endif %}
    </div>
  </section>

</div>

{% endblock %}

base/templates/clinicMedicalSys/login.html
{% extends 'clinicMedicalSys/base.html' %}
{% load static %}

{% block content %}
<style>
  form {
    margin-top: 20px;
  }

  a {
    color: #ffff;
  }

  #id_username {
    width: 100%;
  }

  #id_password {
    width: 100%;
  }
</style>

<h1>Login</h1>

<form method="POST">
  <div class="form-outline mb-4">
    {% csrf_token %}
    {{form.as_p}}

    <!-- Submit button -->
    <button type="submit" value="Login" class="btn btn-primary btn-block mb-4">Sign in</button>
  </div>
</form>
<!-- Register buttons -->
<p><strong>-- OR --</strong></p>
<div class="text-center">
  <button type="submit" value="Login" class="btn btn-link btn-floating mx-1">
    <a href="{% url 'social:begin' backend='facebook' %}">Login com o Facebook</a>
  </button>
</div>

{% endblock %}